# Blog Post 1

## 11 January 2017

The prompt for this week, much like the values laid out in Spiro’s article, are exceptionally broad. Also, I would just like to insert a disclaimer here and note that while I consider myself a historian of literature, I have relatively little training in historiography, and thus believe I am not exactly qualified to talk about the digital humanities values, according to Spiro, and how they should or should not apply to history. Please forgive my literary inclination and flavor in my response. That being said, let’s begin:

Lisa Spiro identifies and proposes several values she believes to be integral to the success of the digital humanities, and which are the result of her dissecting “manifestos, model statements of values” and her own analyses of the way DH presents itself. The values she notes are openness, collaboration, collegiality and connectedness, diversity, and experimentation. After reading Spiro’s piece last week, and having just re-skimmed it, I have to say that I pretty much agree with the value categories she proposes. For openness, the biggest part of what she said that holds true for me is the availability of open-source software tools. When I worked on the team at Vanderbilt University creating the video game based on The Voyage of Saint Brendan, I used Unity, a game building platform that is available to anyone for free. Add-ons, of course, were purchased as needed, but all of us were able to build our literary medieval worlds because of open-access. Here, also, Spiro hits the nail on the head when she says, “Rather than cheapening knowledge by making it free, embracing openness recognizes the importance of the humanities to society.” This is crux, I believe, of the entirety of the digital humanities in my life.

Collaboration, as Spiro points out, is found consistently as a panel at DH conferences. She notes that at least 48% of articles in Literary and Linguistic Computing are coauthored, which is something that is not so common in the traditional world of humanities. Of course, it needs to be noted that just because an article is coauthored does not necessarily indicate a high level of collaboration. BUT I believe that ideas are parsed better when several people are working together. Generally, I think this is a good practice for historians. To return to my example of working on The Voyage of Saint Brendan video game, working as a team was the best, and really only, way to approach its creation. We each have different ways of approaching and analyzing texts, and so if these texts are shaping the DH work we do, then collaboration is a necessity.

I’m going to go ahead and skip collegiality and connectedness because I think, as a rule, we should all be nice and play fair in all our disciplines. Moving along, then, to diversity. Given the overwhelming whiteness and maleness of the academy, scholarship must move toward inclusivity. For history, this means creating, taking part in, or supporting projects that focus on and underscore traditionally neglected or marginalized histories. Here at U-M, the Humanities Collaboratory is an instrumental space for promoting diversity. Some of their current projects include “19th Century Performance Reconstructions: African American and Women Artists,” “Audio Visual Africa,” “Heycho’s Journey,” and “Karanis: Multidisciplinary Approaches to an Egyptian Town” (https://sites.lsa.umich.edu/collaboratory/home/research-projects/) These projects, almost all historically-based, focus on bringing minorities to the forefront of scholarly inquiry. 

The last value Spiro lays out is experimentation. Here, she identifies that not all experiments in the digital humanities have to succeed—she even points out that Two American Communitites on the Eve of the Civil War: An Experiment in Form and Analysis was ultimately rejected because of its use of hypertext, which did not conform to traditional standards of academic writing. Again, Spiro aptly writes, “For the digital humanities community, experimentation suggests not only a method of testing ideas and creating knowledge but also its engagement in transforming traditional approaches to teaching and research.” As with literature, I would argue this is very much the case with history. I imagine what we teach is shaped by what we research, and vice versa. Thus, our creation of knowledge in interpreting the past should be used in new and exciting ways in the classroom, and in ways that change the path of academia.

My dissection of Sprio’s values was really an exercise in being able to suss her assemblage of different perspectives. As I stated before, I agree with these values and believe that they should be at the core of the development and transformation of DH. I’m sure that as I progress through this course, I will be able to provide more cogent opinions on her values and maybe even contribute some of my own.
